# Generated by Django 2.0.1 on 2018-02-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.TextField(null=True, unique=True)),
                ('usability', models.BooleanField(default=True)),
            ],
        ),
    ]
