# Generated by Django 2.0.1 on 2018-01-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name_en', models.TextField(null=True)),
                ('course_name_cn', models.TextField(null=True)),
                ('course_code', models.CharField(default='EMPTY_COURSE_CODE', max_length=32)),
                ('course_units', models.IntegerField()),
                ('course_class', models.CharField(default='DEFAULT_CLASS', max_length=32)),
                ('course_descriptions', models.TextField(null=True)),
            ],
        ),
    ]
