# Generated by Django 2.0.4 on 2018-06-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_en', models.CharField(max_length=128, null=True)),
                ('division_cn', models.CharField(max_length=128, null=True)),
                ('division_en_abbr', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'division',
                'verbose_name_plural': 'divisions',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_en', models.CharField(max_length=128, null=True)),
                ('major_cn', models.CharField(max_length=128, null=True)),
                ('major_en_abbr', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'major',
                'verbose_name_plural': 'majors',
            },
        ),
        migrations.CreateModel(
            name='ValidDivisionMajorPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Division')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Major')),
            ],
        ),
    ]
