# Generated by Django 2.0.4 on 2018-06-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validdivisionmajorpair',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Major', unique=True),
        ),
    ]
