# Generated by Django 2.0.4 on 2018-06-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180607_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validdivisionmajorpair',
            name='major',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Major'),
        ),
    ]
