# Generated by Django 2.0.1 on 2018-02-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursecomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CourseComments',
        ),
    ]
