# Generated by Django 2.0.1 on 2018-02-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180210_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(default='FE', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='course_division',
            field=models.CharField(default='ALL', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='course_major',
            field=models.CharField(default='ALL', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='view_times',
            field=models.IntegerField(default=0),
        ),
    ]
