# Generated by Django 2.0.4 on 2018-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name_cn',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name_abbr',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_en',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_en_abbr',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_en',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_en_abbr',
            field=models.CharField(max_length=128),
        ),
    ]
