# Generated by Django 2.0.4 on 2018-06-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180613_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='', verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='NULL0000', max_length=32, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_major_take',
            field=models.ManyToManyField(to='course.ValidDivisionMajorPair', verbose_name='Major(s) that take this course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name_cn',
            field=models.CharField(max_length=128, verbose_name='Course Chinese Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=128, verbose_name='Course English Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_pre_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course', verbose_name='Course Pre-Request'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.CourseType', verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_units',
            field=models.IntegerField(default=3, help_text='3 Units or 1 Unit', verbose_name='Course Credit'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_rateable',
            field=models.BooleanField(default=True, verbose_name='Rate-ability of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visibility of the course'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Type Name'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name_abbr',
            field=models.CharField(max_length=128, verbose_name='Type Abbreviation'),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_cn',
            field=models.CharField(max_length=128, verbose_name='Division Chinese Title'),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_en',
            field=models.CharField(max_length=128, verbose_name='Division English Title'),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_en_abbr',
            field=models.CharField(max_length=128, verbose_name="Abbreviation for Division's English Title"),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_cn',
            field=models.CharField(max_length=128, verbose_name='Major Chinese Title'),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_en',
            field=models.CharField(max_length=128, verbose_name='Major English Title'),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_en_abbr',
            field=models.CharField(max_length=128, verbose_name="Abbreviation for Major's English Title"),
        ),
    ]
