# Generated by Django 2.0.1 on 2018-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180212_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_division',
            field=models.CharField(choices=[('DST', 'Division of Science and Technology'), ('DBM', 'Division of Business and Management'), ('DHSS', 'Division of Humanities and Social Sciences'), ('DCC', 'Division of Culture and Creativity'), ('ALL', 'All Division')], default='ALL', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_major',
            field=models.CharField(choices=[('DST', (('FST', 'Food Science and Technology'), ('ENVS', 'Environmental Science'), ('APSY', 'Applied Psychology'), ('STAT', 'Statistics'), ('FM', 'Financial Mathematics'), ('CST', 'Computer Science and Technology'), ('DS', 'Data Science'))), ('DBM', (('ACCT', 'Accounting'), ('FIN', 'Finance'), ('AE', 'Applied Economics'), ('EBIS', 'e-Business Management and Information Systems'), ('MHR', 'Management of Human Resources'), ('MKT', 'Marketing Management'), ('EPIN', 'Entrepreneurship and Innovation'))), ('DCC', (('CCM', 'Culture, Creativity and Management'), ('CTV', 'Cinema and Television'), ('MAD', 'Media Arts and Design'))), ('DHSS', (('GIR', 'Government and International Relations'), ('SWSA', 'Social Work and Social Administration'), ('IJ', 'International Journalism'), ('PRA', 'Public Relations and Advertising'), ('ATS', 'Applied Translation Studies '), ('ELLS', 'English Language and Literature Studies'))), ('ALL', 'ALL Major')], default='ALL', max_length=32),
        ),
    ]
