# Generated by Django 2.0.1 on 2018-02-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20180212_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_class',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('BBAC', 'BBA (Hons) Core'), ('MR', 'Major Required'), ('ME', 'Major Elective'), ('GEC', 'General Education Core'), ('GED', 'General Education Distribution'), ('WPEX', 'Whole Person Education Experiential Learning Modules'), ('FE', 'Free Elective')], default='FE', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='EMPY1003', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_descriptions',
            field=models.TextField(default='To be added', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_units',
            field=models.IntegerField(choices=[(3, 'Three Units'), (1, 'One Unit')], default=3),
        ),
    ]
