# Generated by Django 2.0.1 on 2018-02-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180212_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name_cn',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
