# Generated by Django 2.0.1 on 2018-02-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20180212_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_class',
            field=models.CharField(default='DEFAULT_CLASS', max_length=32),
        ),
    ]
