# Generated by Django 2.0.1 on 2018-02-28 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_course_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pre_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
