# Generated by Django 2.0.1 on 2018-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_quickvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name_en', models.CharField(max_length=128, null=True)),
                ('tag_name_cn', models.CharField(max_length=128, null=True)),
                ('tag_descriptions', models.TextField(default='To be added', null=True)),
                ('tag_weighted', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='is_display_score',
            field=models.BooleanField(default=True),
        ),
    ]
