# Generated by Django 2.0.1 on 2018-03-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_invitationcode_who_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationcode',
            options={'ordering': ['usability']},
        ),
    ]
