# Generated by Django 2.0.1 on 2018-03-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20180310_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationcode',
            options={'ordering': ['-usability']},
        ),
    ]
