# Generated by Django 2.2.2 on 2019-07-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0009_auto_20180616_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=128, verbose_name='Item English Title')),
                ('title_cn', models.CharField(max_length=128, verbose_name='Item Chinese Title')),
                ('unit', models.IntegerField(default=3, help_text='Unit for this item', verbose_name='Item Credit')),
                ('admission_year', models.PositiveSmallIntegerField(default=2005, verbose_name='Admission Year that item belongs')),
                ('study_semester', models.PositiveSmallIntegerField(default=1, verbose_name='Semester of this item')),
                ('comment', models.CharField(max_length=512, verbose_name='More info about this item')),
                ('is_course_category', models.BooleanField(default=False, verbose_name='Is this item a a course category')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ValidDivisionMajorPair')),
            ],
            options={
                'ordering': ['-admission_year', 'study_semester'],
            },
        ),
    ]
