# Generated by Django 2.2.2 on 2019-07-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handbookentity',
            options={'ordering': ['-admission_year', 'study_semester', 'priority']},
        ),
    ]
