# Generated by Django 2.2.2 on 2019-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_auto_20190703_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbookentity',
            name='comment',
            field=models.CharField(blank=True, max_length=512, verbose_name='More info about this item'),
        ),
    ]
