# Generated by Django 2.0.4 on 2018-06-13 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickvotes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Voting Course'),
        ),
        migrations.AlterField(
            model_name='quickvotes',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Voter'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_description',
            field=models.TextField(default='', verbose_name='Tag Description'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_sentiment_index',
            field=models.FloatField(default=0, help_text='Positive number for positive emotions; Negative number for negative emotions, 0 for neutral emotion', verbose_name='Tag Sentiment Index'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Tag Title'),
        ),
    ]
