# Generated by Django 2.0.4 on 2018-06-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180613_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickvotes',
            options={'verbose_name': 'Quick Vote', 'verbose_name_plural': 'Quick Votes'},
        ),
    ]
