# Generated by Django 2.0.6 on 2018-06-14 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_auto_20180613_2156'),
        ('voting', '0005_auto_20180613_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaggingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_date', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tag_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tags', to='course.Course', verbose_name='Tagging course')),
                ('tagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Course Tagger')),
                ('tags', models.ManyToManyField(to='voting.Tags', verbose_name="User's tag(s) for this course")),
            ],
            options={
                'verbose_name_plural': 'User Reviews',
                'verbose_name': 'User Review',
            },
        ),
    ]
