# Generated by Django 3.2.4 on 2021-06-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_usertaggingcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickvotes',
            name='vote_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
