# Generated by Django 3.2.4 on 2021-06-26 03:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0009_auto_20180616_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_time', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Lecture workload')),
                ('tutorial_time', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tutorial workload')),
                ('project_time', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Project workload')),
                ('preparation_time', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preparation workload')),
                ('lab_time', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Lab workload')),
                ('homework_time', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Homework workload')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'course workload',
                'verbose_name_plural': 'course workload',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.BooleanField(default=False)),
                ('assignment', models.BooleanField(default=False)),
                ('essay', models.BooleanField(default=False)),
                ('project', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=False)),
                ('reading_material', models.BooleanField(default=False)),
                ('presentation', models.BooleanField(default=False)),
                ('mid_term_Exam', models.BooleanField(default=False)),
                ('final_exam', models.BooleanField(default=False)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'course module',
                'verbose_name_plural': 'course module',
            },
        ),
    ]
